services:
  service_hrrr_historical:
    build: . 
    image: twatlebob/hrrr_historical:latest2
    container_name: container_hrrr_historical
    environment:
      TZ: ${TZ:-America/Chicago}
    volumes:
      - E:\DATA\hrrr_historical:/hrrr_historical/data
    restart: unless-stopped